server:
  port: 8080
  servlet:
    context-path: /BB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bumblebee
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

security:
  allowed-credentials: true
  allowed-origins:
    - http://localhost:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - POST
  allowed-headers:
    - Authorization
    - origin
    - Content-type
    - Accept
    - Accept-Control-Allow-Origin
    - Accept-Control-Allow-Header
    - Accept-Control-Request-Method
    - X-Xsrf-Token
  exposed-headers:
    - X-Xsrf-Token
  valid-application-roles:
    - ROLE_SUPER_ADMIN
    - ROLE_ADMIN
    - ROLE_USER

